/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#234e43",
        "background": "#0b1513",
        "primary-fixed": "#7ef6ed",
        "surface-container-low": "#131d1b",
        "error": "#ffb4ab",
        "outline": "#869392",
        "tertiary-container": "#d6c5a1",
        "on-primary-fixed-variant": "#00504c",
        "on-surface": "#dae5e1",
        "surface-container": "#17221f",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "inverse-on-surface": "#283230",
        "on-tertiary": "#392f16",
        "surface": "#0b1513",
        "on-surface-variant": "#bcc9c7",
        "on-secondary-fixed": "#002019",
        "surface-tint": "#5fd9d1",
        "on-tertiary-fixed-variant": "#51462a",
        "outline-variant": "#3d4948",
        "surface-dim": "#0b1513",
        "tertiary-fixed": "#f3e1bb",
        "primary-container": "#5fd9d1",
        "surface-container-high": "#222c2a",
        "on-background": "#dae5e1",
        "on-primary-fixed": "#00201e",
        "on-secondary-container": "#94c2b3",
        "surface-bright": "#313b39",
        "secondary": "#a2d0c1",
        "tertiary": "#f3e1bc",
        "on-tertiary-container": "#5d5135",
        "surface-container-highest": "#2d3734",
        "on-error": "#690005",
        "on-primary-container": "#005d58",
        "secondary-fixed": "#beecdc",
        "on-tertiary-fixed": "#231a04",
        "surface-variant": "#2d3734",
        "on-primary": "#003734",
        "primary-fixed-dim": "#5fd9d1",
        "secondary-fixed-dim": "#a2d0c1",
        "primary": "#7ef6ed",
        "secondary-container": "#255145",
        "tertiary-fixed-dim": "#d6c5a1",
        "surface-container-lowest": "#06100e",
        "on-secondary": "#07372d",
        "inverse-surface": "#dae5e1",
        "inverse-primary": "#006a65"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter-desktop": "1.5rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "gutter": "1rem",
        "margin": "1rem",
        "margin-desktop": "2rem"
      },
      fontFamily: {
        "label-lg": ["JetBrains Mono", "monospace"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "display": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", fontWeight: "400" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "0em", fontWeight: "500" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.06em", fontWeight: "400" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.04em", fontWeight: "500" }],
        "display": ["3.5rem", { lineHeight: "4rem", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-lg": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["0.9375rem", { lineHeight: "1.5rem", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
